version: '3'
services:
  web:
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=BIB_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pi3rreLoui$
      - POSTGRES_PORT=5432
  postgres:
    image: postgres:alpine3.17
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=BIB_DB
      - POSTGRES_PASSWORD=Pi3rreLoui$
